In [1]:
a = float(input("Nhap gia tri a"))
b= float(input("Nhap gia tri b"))
tong = a + b
hieu = a - b
thuong = a / b
tich = a * b
print("Tong a va b la: ", tong)
print("Hieu a va b la:", hieu)
print("Thuong a va b la:", thuong)
print("tich a va b la:", tich)
if b != 0:
    thuong = a / b
    print(f"Thương của {a} và {b} là: {thuong}")
else:
    print("Không thể tính thương vì số chia (b) bằng 0.")

Nhap gia tri a12
Nhap gia tri b16
Tong a va b la:  28.0
Hieu a va b la: -4.0
Thuong a va b la: 0.75
tich a va b la: 192.0
Thương của 12.0 và 16.0 là: 0.75


In [2]:
text = "Hello World"
result = text[2:5]
print(result)

llo


In [3]:
s = "   Hello World  "
s = s.strip()
print(s.upper())
print(s.lower())
print(s.replace("H", "J"))

HELLO WORLD
hello world
Jello World


In [6]:
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
if a > b:
  print("Hello World!")

Nhập a: 13
Nhập b: 11
Hello World!


In [7]:
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))

print("Yes") if a == b else print("No")

Nhập a: 12
Nhập b: 16
No


In [8]:
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
c = float(input("Nhập c: "))
d = float(input("Nhập d: "))
if a == b and b == d: print("Hello World!")

Nhập a: 16
Nhập b: 16
Nhập c: 16
Nhập d: 16
Hello World!


In [9]:
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))

print("Yes") if a > b else print("No")


Nhập a: 16
Nhập b: 12
Yes


In [10]:
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))

print("A") if a > b else print("=") if a == b else print("B")

Nhập a: 13
Nhập b: 15
B


In [11]:
import numpy as np

n = int(input("Nhập số phần tử n: "))
a = np.random.randint(1, 100, n)
filter_arr = (a % 2 == 0)
b = a[filter_arr]
print("Mảng a:", a)
print("Mảng b (các phần tử chẵn):", b)

Nhập số phần tử n: 3
Mảng a: [46 99  8]
Mảng b (các phần tử chẵn): [46  8]


In [12]:
tong = 0

for i in range(1000):
    if i % 3 == 0 or i % 5 == 0:
        tong += i

print(f"Tổng các số từ 0 đến 999 là bội của 3 hoặc 5 là: {tong}")

Tổng các số từ 0 đến 999 là bội của 3 hoặc 5 là: 233168


In [13]:
def tron_mang(a, b):
    min_len = len(a) if len(a) < len(b) else len(b)

    res = b[:] if len(b) > len(a) else a[:]

    for i in range(min_len):
        res[i] = a[i] + b[i]

    return res
a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]
print("Mảng a:", a)
print("Mảng b:", b)
print("Mảng kết quả:", tron_mang(a, b))

Mảng a: [3, 9, 1, 4]
Mảng b: [2, 7, 4, 3, 2, 8]
Mảng kết quả: [5, 16, 5, 7, 2, 8]


In [14]:
import numpy as np

def tao_mang(m, n):
    return np.random.randint(1, 101, size=(m, n))

def xuat_dong_k(a, k):
    if k < a.shape[0]:
        print(f"Các phần tử thuộc dòng {k}: {a[k, :]}")
    else:
        print("Chỉ số dòng không hợp lệ")

def xuat_cot_k(a, k):
    if k < a.shape[1]:
        print(f"Các phần tử thuộc cột {k}: {a[:, k]}")
        print("Chỉ số cột không hợp lệ")

def dong_tong_lon_nhat_45(a):
    tong_cac_dong = a.sum(axis=1)
    dong_thoa_man = tong_cac_dong[tong_cac_dong <= 45]
    if dong_thoa_man.size > 0:
        max_val = dong_thoa_man.max()
        index = np.where(tong_cac_dong == max_val)[0]
        print(f"Dòng có tổng lớn nhất (<=45) là dòng {index} với tổng = {max_val}")
    else:
        print("Không có dòng nào có tổng <= 45")

def cot_tich_nho_nhat(a):
    tich_cac_cot = a.prod(axis=0)
    index_min = np.argmin(tich_cac_cot)
    print(f"Cột có tích nhỏ nhất là cột {index_min} với tích = {tich_cac_cot[index_min]}")

def dong_chan_cot_le(a):
    kq = a[0::2, 1::2]
    print("Các phần tử thuộc dòng chẵn và cột lẻ:\n", kq)

def tbc_chan_dong_le(a):
    dong_le = a[1::2, :]
    phan_tu_chan = dong_le[dong_le % 2 == 0]
    if phan_tu_chan.size > 0:
        print(f"Trung bình cộng phần tử chẵn thuộc dòng lẻ: {phan_tu_chan.mean()}")
    else:
        print("Không có phần tử chẵn nào ở dòng lẻ")

def tbc_bien(a):
    m, n = a.shape
    mask = np.ones((m, n), dtype=bool)
    mask[1:-1, 1:-1] = False
    bien = a[mask]
    print(f"Trung bình cộng các phần tử biên: {bien.mean()}")

def trung_binh_tich_loi(a):
    loi = a[1:-1, 1:-1]
    if loi.size > 0:
        tich = loi.prod()
        print(f"Tích các phần tử lõi: {tich}")
    else:
        print("Ma trận quá nhỏ, không có phần tử lõi")

m, n = 4, 5
mang_a = tao_mang(m, n)
print("Ma trận a:\n", mang_a)

xuat_dong_k(mang_a, 1)
dong_tong_lon_nhat_45(mang_a)
cot_tich_nho_nhat(mang_a)
dong_chan_cot_le(mang_a)
tbc_chan_dong_le(mang_a)
tbc_bien(mang_a)
trung_binh_tich_loi(mang_a)

Ma trận a:
 [[ 3 14 26 48 52]
 [49 57 30 69  9]
 [64 51 42 22 89]
 [55 69  2 77 51]]
Các phần tử thuộc dòng 1: [49 57 30 69  9]
Không có dòng nào có tổng <= 45
Cột có tích nhỏ nhất là cột 2 với tích = 65520
Các phần tử thuộc dòng chẵn và cột lẻ:
 [[14 48]
 [51 22]]
Trung bình cộng phần tử chẵn thuộc dòng lẻ: 16.0
Trung bình cộng các phần tử biên: 43.42857142857143
Tích các phần tử lõi: 5560160760


In [ ]:
import datetime

class SinhVien:
    def __init__(self, ma_sv, ten, nam_sinh, dtb):
        self.ma_sv = ma_sv[:10]
        self.ten = ten[:20]
        self.nam_sinh = int(nam_sinh)
        self.dtb = float(dtb)

    def __str__(self):
        return f"MSV: {self.ma_sv} | Tên: {self.ten} | Năm sinh: {self.nam_sinh} | ĐTB: {self.dtb}"

    @staticmethod
    def nhap_danh_sach_sv(n):
        ds_sv = []
        for i in range(n):
            print(f"Nhập thông tin sinh viên thứ {i+1}:")
            ma = input("Mã SV: ")
            ten = input("Tên SV: ")
            nam = int(input("Năm sinh: "))
            diem = float(input("Điểm TB: "))
            ds_sv.append(SinhVien(ma, ten, nam, diem))
        return ds_sv

    @staticmethod
    def dem_sv_len_lop(ds_sv):
        count = sum(1 for sv in ds_sv if sv.dtb >= 5)
        return count

    @staticmethod
    def xuat_sv_20_tuoi(ds_sv):
        nam_hien_tai = datetime.datetime.now().year
        print("Danh sách sinh viên đủ 20 tuổi:")
        for sv in ds_sv:
            if nam_hien_tai - sv.nam_sinh >= 20:
                print(sv)

    @staticmethod
    def dem_sv_he_dh(ds_sv):
        count = 0
        for sv in ds_sv:
            if sv.ma_sv[2:4].upper() == "DH":
                count += 1
        return count

    @staticmethod
    def dem_ten_lan(ds_sv):
        return sum(1 for sv in ds_sv if sv.ten.split()[-1].lower() == "lan")

    @staticmethod
    def dem_ho_phan(ds_sv):
        return sum(1 for sv in ds_sv if sv.ten.split()[0].lower() == "phan")

n = int(input("Nhập số lượng sinh viên: "))
danh_sach = SinhVien.nhap_danh_sach_sv(n)

print(f"\nSố SV đủ điều kiện lên lớp: {SinhVien.dem_sv_len_lop(danh_sach)}")
SinhVien.xuat_sv_20_tuoi(danh_sach)
print(f"Số SV hệ Đại học: {SinhVien.dem_sv_he_dh(danh_sach)}")
print(f"Số SV tên Lan: {SinhVien.dem_ten_lan(danh_sach)}")
print(f"Số SV họ Phan: {SinhVien.dem_ho_phan(danh_sach)}")